### ISSUE TITLE
openmoji.json causes issues

### ISSUE THREAD

**Issue by Sam0711er** [hfg-gmuend/openmoji-stickers-ios#10]
Within the `openmoji.json` file the following issues appear:

1. The `skintone` property is somtimes of type `String`, sometimes of type `Int`. A definitive declaration as String would be great (Swift requires type safety)
2. After the Wales flag (🏴󠁧󠁢󠁷󠁬󠁳󠁿, `1F3F4-E0067-E0062-E0077-E006C-E0073-E007F`), `order` no. 4702, items don't have an order number anymore. This however is essential to be able to order the emojis on the app. I suppose these are all custom emojis that are not part of unicode.

In order to perform these changes, the files needs to be changed in the main repo, as it is only copied over from that repo: https://github.com/hfg-gmuend/openmoji/blob/master/data/openmoji.json

**Comment by b-g** [comment]
@Sam0711er Done. OK?
