### ISSUE TITLE
Bug: App crashes when trying to copy directly from the app via share menu

### ISSUE THREAD

**Issue by fabianmoronzirfas** [hfg-gmuend/openmoji-stickers-ios#5]
![C4FD9F08-008A-460B-AA0D-1DBC9854F695](https://user-images.githubusercontent.com/315106/57999621-4de5b300-7ad6-11e9-9ffe-3a8315e61e42.gif)

**Comment by Sam0711er** [comment]
Hey @fabianmoronzirfas! Thanks for sharing this. Which App version are you running? This bug should be fixed in v1.0.2

**Comment by fabianmoronzirfas** [comment]
Yes. You are right. I was on an old version. Fixed.
